[request_definition]
r = role, routes, HTTPMethod

[policy_definition]
p = role, routes, HTTPMethod

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.role == p.role && r.routes == p.routes && r.HTTPMethod == p.HTTPMethod